FROM websphere-liberty:webProfile7
MAINTAINER IBM Java engineering at IBM Cloud

RUN echo "nameserver 10.0.0.10" >> /etc/resolv.conf

RUN mkdir -m 777 -p /config/resources

# Upgrade to production license if URL to JAR provided
ARG LICENSE_JAR_URL
RUN \
  if [ $LICENSE_JAR_URL ]; then \
    wget $LICENSE_JAR_URL -O /tmp/license.jar \
    && java -jar /tmp/license.jar -acceptLicense /opt/ibm \
    && rm /tmp/license.jar; \
  fi
